name: maquina_refrigerante_flutter
description: Máquina refrigerante.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  json_annotation: ^4.8.1
  json_serializable: ^6.5.4
  dio: ^4.0.6
  get_it: ^7.2.0
  build_runner: ^2.3.3

  maquina_refrigerante:
    path: ../maquina_refrigerante_dart

  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
  - assets/image/

  fonts:
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo2-Regular.ttf
          weight: 500
